spring:
  application:
    name: ccbrkr
  main:
    allow-bean-definition-overriding: true

#resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberofCalls: 2
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
    instances:
      purchaseBreaker:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"