spring:
  application:
    name: ccbrkr
  main:
    allow-bean-definition-overriding: true

#resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true  #true? ? Health Indicator? ???? Circuit Breaker? ??? ???? ? ? ??.
        slidingWindowSize: 10          #Circuit Breaker? ??? ??? ? ??? ??? ?? ?? ?? 10?? ?? 10?? ??? ???? ?? ??
        minimumNumberofCalls: 5        #Circuit Breaker? ??? ???? ?? ???? ?? ?? ?????. ? ?? ??? ??? ??? ?? ??? ???? ????.
        permittedNumberOfCallsInHalfOpenState: 3 #Half-Open???? ???? ?? ?, ? ??? ? ?? ?? ? Closed ??? ??
        automaticTransitionFromOpenToHalfOpenEnabled: true #Open???? ???? Half-Open??? ??, ??? ???? ?????
        waitDurationInOpenState: 5s #Open??? ???? ?? ?? 5??? Half-Open??? ??
        failureRateThreshold: 50 #??? ???, ?? ? Open??? ?? -> 50%??? ?? ?? ? Open ??? ??
        eventConsumerBufferSize: 10 #CircuitBreaker? ??? ??? ?? ??? ??, ??? ?? ? ???? ??? ? ?? ?? ??? ?? ???
        ignoreException: #?? ??? ??? ? ??? ?? ??? ??? ???? Open??? ??????
          - java.util.NoSuchElementException

    instances:
      order:
        minimumNumberOfCalls: 10 #CircuitBreaker? ??? ???? ?? ?? 10?? ??? ??
        waitDurationInOpenState: 3s #Open???? 3?? ??? Half-Open??? ??
        failureRateThreshold: 10 # ???? 10%? ???? Open ??? ??
      purchaseBreaker:
        baseConfig: default #? ????? ?? ??? ??? ??? ???